# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 17:28
from __future__ import unicode_literals

import Player.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('is_incog', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', Player.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='char',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='current_char',
            field=models.ForeignKey(help_text='This is the char name that displays when the player comments on a log', null=True, on_delete=django.db.models.deletion.CASCADE, to='Player.Char'),
        ),
    ]
