# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_install_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCharRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=43)),
                ('player', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pendingcharregistration',
            unique_together=set([('player', 'name')]),
        ),
    ]
